name: chatui
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://github.com/yourusername/your-repo"

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  any_link_preview: ^3.0.3
  cached_network_image: ^3.3.0
  emoji_picker_flutter: ^1.6.3
  geolocator: ^13.0.1
  intl: ^0.20.1
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  dart_mappable: ^4.6.0
  screwdriver: ^5.10.0
  flutter_screwdriver: ^3.2.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  mime: ^2.0.0
  path: ^1.9.0
  infinite_scroll_pagination: ^5.1.1
  visibility_detector: ^0.4.0+2
  flutter_keyboard_visibility: ^6.0.0
  swipe_to: ^1.0.6
  video_player: ^2.7.0
  open_file_plus: ^3.4.1

  audioplayers: ^5.1.0
  flutter_sound: ^9.2.13
  audio_session: ^0.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  dart_mappable_builder: ^4.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/landing_img.png
    - assets/images/PENDING.png
    - assets/images/SENT.png
    - assets/images/DELIVERED.png
    - assets/images/SEEN.png
    - assets/images/dark/chat_bg.png
    - assets/images/chat_bg.png
    - assets/images/logo.png
    - assets/images/avatar.png
