name: chat_interface
description: "A flexible, production-ready chat UI for Flutter with paging, attachments, reactions, and theming."
version: 0.0.4
repository: "https://github.com/itsarvinddev/chat_interface"
issue_tracker: "https://github.com/itsarvinddev/chat_interface/issues"
documentation: "https://github.com/itsarvinddev/chat_interface#readme"
topics:
  - chat
  - user-interface
  - messaging
  - widgets

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  any_link_preview: ^3.0.3
  cached_network_image: ^3.4.1
  intl: ^0.20.1
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  dart_mappable:
    git:
      url: https://github.com/itsarvinddev/dart_mappable.git
      ref: 764569bb1cc731f869713b655c15209b9c0abad8
      path: packages/dart_mappable
  screwdriver: ^5.10.0
  flutter_screwdriver: ^3.2.0
  dio: ^5.9.0
  path_provider: ^2.1.5
  mime: ^2.0.0
  path: ^1.9.1
  infinite_scroll_pagination: ^5.1.1
  visibility_detector: ^0.4.0+2
  flutter_keyboard_visibility: ^6.0.0
  swipe_to: ^1.0.6
  # video_player: ^2.7.0
  share_plus: ^12.0.0

  # audioplayers: ^5.1.0
  # flutter_sound: ^9.2.13
  # audio_session: ^0.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  dart_mappable_builder:
    git:
      url: https://github.com/itsarvinddev/dart_mappable.git
      ref: 7998e7f0f2e66f9a65215ff7f43dc603d7b6d883
      path: packages/dart_mappable_builder

dependency_overrides:
  dart_mappable:
    git:
      url: https://github.com/itsarvinddev/dart_mappable.git
      ref: 7998e7f0f2e66f9a65215ff7f43dc603d7b6d883
      path: packages/dart_mappable

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/landing_img.png
    - assets/images/PENDING.png
    - assets/images/SENT.png
    - assets/images/DELIVERED.png
    - assets/images/SEEN.png
    - assets/images/image.png
    - assets/images/avatar.png

screenshots:
  - description: "Chat list and composer with message statuses and attachments"
    path: IMG_5624.png
  - description: "Chat list and composer with message statuses and attachments"
    path: IMG_5625.png
  - description: "Chat list and composer with message statuses and attachments"
    path: IMG_5626.png
